
#-------------Attendance-----------

### get all Attendance.
GET http://localhost:8000/api/attendance/getAll

### get Attendance By ID.
GET http://localhost:8000/api/attendance/getattendanceByID/2


### get Attendance By Employee ID.
GET http://localhost:8000/api/attendance/getattendanceByEmpID/2



### Delete Attendance .
DELETE http://localhost:8000/api/attendance/deleteattendanceByID/4



### Add New Attendance
POST http://localhost:8000/api/attendance/AddAttendance
Content-Type: application/json

{
    "EmployeeID": 2,
    "ScheduleID": 1,
    "TimeIn": "08:00:00"      
}

### Update Attendance by ID
PUT http://localhost:8000/api/attendance/UpdateAttendanceByID/115
Content-Type: application/json

{
    "EmployeeID": 2,
    "Date": "2024-03-18",
    "ScheduleID": 1,
    "TimeIn": "08:00:00AM",
    "TimeOut": "011:00:00AM",
    "Hours": "10"
}






# {
#     "EmployeeID": 2,
#     "Date": "2024-03-18",
#     "ScheduleID": 1,
#     "TimeIn": "08:00:00AM",
#     "TimeOut": "14:00:00.000Z",
#     "Hours": "5"
# }

