
#-------------Schedules-----------

### get all Schedules.
GET http://localhost:8000/api/Schedules/getAll

### get Schedule By ID.
GET http://localhost:8000/api/Schedules/getScheduleByID/6


### Delete Schedule .
DELETE http://localhost:8000/api/Schedules/deleteSchedule/6


