### Health check
GET http://localhost:8000/health


#-------------user---------

### Add New Employee
POST http://localhost:8000/api/users/addNewEmployee
Content-Type: application/json

{
    "FirstName" : "Fank",
    "LastName" : "Munyoki",
    "Location" : "Nyeri",
    "BirthDate" : "2000-05-10",
    "Contact" : "0735621144",
    "Gender" : "Male",
    "admin" : false ,
    "PositionID" : 1,
    "ScheduleID" : 1,
    "PhotoURL" : "https://example.com/john.jpg",
    "Email" : "franch@gmail.com",
    "Password" : "password111",
    "BankName" : "NCBA",
    "BankBranch" : "Nyeri",
    "AccountNumber" : "12354321",
    "Bio" : "Meet From Munyoki fro Moringa"
}

### getting All users
GET http://localhost:8000/api/users/getAllUsers

### getting User By ID
GET http://localhost:8000/api/users/getUserByID/4

### login
POST http://localhost:8000/api/users/login
Content-Type: application/json

{
    "Email" : "john@example.com",
    "Password" : "password123"
}


### Update Employee ---where id is.....
PUT http://localhost:8000/api/users/UpdateEmployeeByID/4
Content-Type: application/json

{
    "FirstName" : "Titus",
    "LastName" : "Munyoki",
    "Location" : "Nyeri",
    "BirthDate" : "2000-05-10",
    "Contact" : "0735621144",
    "Gender" : "Male",
    "admin" : 0,
    "PositionID" : 1,
    "ScheduleID" : 1,
    "PhotoURL" : "https://example.com/john.jpg",
    "Email" : "pientopitelo@gmail.com",
    "Password" : "password110",
    "BankName" : "NCBA",
    "BankBranch" : "Nyeri",
    "AccountNumber" : "12354321",
    "Bio" : "Meet Titus Munyoki from Moringa"
}







###delete employee
DELETE http://localhost:8000/api/users/deleteEmployeeById/5
